### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by onlyyou** [rytilahti/python-yeelightbt#25] opened 2018-11-11 16:25 UTC
hey,
everything seems fine when install, but can't succeed to make it works...
thanks

`
pi@raspberrypi:~ $ yeelightbt
Traceback (most recent call last):
  File "/usr/local/bin/yeelightbt", line 11, in <module>
    load_entry_point('python-yeelightbt==0.0.3.1', 'console_scripts', 'yeelightbt')()
  File "/home/pi/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/pi/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/home/pi/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/home/pi/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/pi/.local/lib/python3.5/site-packages/yeelightbt/__init__.py", line 2, in <module>
    from .lamp import Lamp
  File "/home/pi/.local/lib/python3.5/site-packages/yeelightbt/lamp.py", line 7, in <module>
    from .structures import Request, Response, StateResult
  File "/home/pi/.local/lib/python3.5/site-packages/yeelightbt/structures.py", line 4, in <module>
    from construct import (Struct, Int8ub, Int16ub, Const, Padded, Byte, Enum, Bytes, If, FlagsEnum,
ImportError: cannot import name 'SymmetricMapping'
`

**Comment by rytilahti** [comment] 2018-11-11 16:50
Duplicate of #18.

**Closed as completed by rytilahti** 2018-11-11 16:50 UTC
