### ISSUE TITLE
Cannot import name 'SymmetricMapping'

### ISSUE THREAD

**Issue by t871631092** [rytilahti/python-yeelightbt#18] opened 2018-03-09 15:01 UTC
2018-03-09 14:57:14 ERROR (Thread-19) [custom_components.light.yeelight_bt] Got exception: cannot import name 'SymmetricMapping'
2018-03-09 14:57:14 INFO (MainThread) [homeassistant.core] Bus:Handling <Event system_log_event[L]: source=custom_components/light/yeelight_bt.py, exception=, level=ERROR, timestamp=1520607434.851715, message=Got exception: cannot import name 'SymmetricMapping'>
## 
I can‘t find the SymmetricMapping by anyway，I'm crazy

**Comment by hcoohb** [comment] 2018-03-12 00:45
I have the same error.
Is it because of construct 2.9.37 ? (which is upgraded if you do an upgrade from git)

**Comment by t871631092** [comment] 2018-03-12 01:55
I have installed the 2.9.25  Should i upgrade ？

**Comment by cwt0490** [comment] 2018-03-13 15:52
https://github.com/rytilahti/python-yeelightbt/issues/17

this should explain why.

what i did is just call 
  pip install construct==2.9.25

which is downgrade to 2.9.25

**Comment by t871631092** [comment] 2018-03-14 04:58
it work on my first time run hass --open-ui
then the second time i run 
it error again

**Comment by hcoohb** [comment] 2018-04-03 04:42
Construct is now pinned at 2.9.41 on home assistant.

But yeelightbt is still showing the same error.
(And the code from the Pull Request 16 is not working either)
Anyone could point us in the right direction ?

**Comment by olskar** [comment] 2018-05-01 21:18
I have the same issue

**Comment by frittes** [comment] 2018-06-09 13:47
Any chance to solve this issue in the near future?

**Comment by DanAE111** [comment] 2018-07-12 23:17
Same for me. Even if you downgrade if you're using home assistant this will break other components.

**Comment by arekbulski** [comment] 2018-07-21 16:35
In some recent Construct version, SymmetricMapping was renamed to Mapping. This error is caused by using an outdated version.

**Comment by rytilahti** [comment] 2018-07-21 20:12
The fix is being worked in #19, but it's a bit slow process as I'm busy with other things currently. If someone wants to step up and finish that porting, it'd be more than welcome.

**Comment by onlyyou** [comment] 2018-11-11 17:02
hey,
did make commande
pip install construct==2.9.25
but still have error
pi@raspberrypi:~ $ yeelightbt scan
Traceback (most recent call last):
  File "/usr/local/bin/yeelightbt", line 11, in <module>
    load_entry_point('python-yeelightbt==0.0.3.1', 'console_scripts', 'yeelightbt')()
  File "/home/pi/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/pi/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2725, in load_entry_point
    return ep.load()
  File "/home/pi/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2343, in load
    return self.resolve()
  File "/home/pi/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2349, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/pi/.local/lib/python3.5/site-packages/yeelightbt/__init__.py", line 2, in <module>
    from .lamp import Lamp
  File "/home/pi/.local/lib/python3.5/site-packages/yeelightbt/lamp.py", line 7, in <module>
    from .structures import Request, Response, StateResult
  File "/home/pi/.local/lib/python3.5/site-packages/yeelightbt/structures.py", line 4, in <module>
    from construct import (Struct, Int8ub, Int16ub, Const, Padded, Byte, Enum, Bytes, If, FlagsEnum,
ImportError: cannot import name 'SymmetricMapping'


thanks

**Comment by lasry1** [comment] 2019-02-11 09:34
I have the same problem, i've installed the plugin with custom deps deployment (i'm running Hassio with HA 0.87.0) but i can't make the light available...

**Comment by Thieum64** [comment] 2019-02-26 20:39
Hi, 
It seems to be a good script to control Candela but I'm facing the same issue 'ImportError: cannot import name 'SymmetricMapping' when trying to install it. 
Is there a way to workarround ? 
Thanks

**Comment by rytilahti** [comment] 2019-02-26 22:14
So I just merged the changes and the code is where I left it long time ago. The basic functionality should work by using the command line tool for what it's worth, maybe someone finds this useful and creates PRs to fix other issues (esp. the homeassistant parts require work to make it usable), I have no personal interest on working further on this.

**Closed as completed** 2019-02-26 22:15 UTC
